name: SpaceBasic Auto Booking

on:
  schedule:
    - cron: '15 4 * * *'  # Runs every day at 9:45 AM IST (4:15 AM UTC)
  workflow_dispatch:      # Allows you to click a button to run it manually anytime!

jobs:
  book-meals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run booking script
        env:
          SPACEBASIC_TOKEN: ${{ secrets.SPACEBASIC_TOKEN }}
        run: python main.py
